### ISSUE TITLE
Wallet crashing after sending money from multiple addresses

### ISSUE THREAD

**Issue by Yoldark34** [PaycoinFoundation/paycoin#463] opened 2016-01-21 18:07 UTC
Machine: Windows 7

**Scenario**
Use coin control and select **30** different addresses (it may not need 30 addresses exactly).
The wallet will display the amount you can send by subtracting the transaction fees.
Use this amount and send the money to a valid address.

The wallet say that there is not enough money for the transaction, 0.001 XPY is missing.
Subtract 0.001 XPY from the amount you expect to send (the wallet will display in red that there will be 0.001 XPY left.)
Validate the transaction (there will be enough fees for the transaction now).

**Expected behaviour**
The transaction is finalized.

**Current behaviour**
The wallet is crashing.

[debug_crash.log.txt](https://github.com/PaycoinFoundation/paycoin/files/99880/debug_crash.log.txt)

**Comment by IngCr3at1on** [comment] 2016-01-21 20:32
Most likely a duplicate of #456

**Comment by Yoldark34** [comment] 2016-01-21 20:34
There is not enough details on the 456 so it may not be the same bug.

**Comment by IngCr3at1on** [comment] 2016-01-21 20:36
@Yoldark34 there's in fact a debug log so in some respect there is more detail :P
You'll note I didn't mark it as a duplicate I just said it most likely was.
That can be confirmed by checking the last thing in the debug log to see if it is crashing in the same spot.

**Comment by Yoldark34** [comment] 2016-01-21 20:38
I will reproduce it and give you the log :+1: .

**Comment by IngCr3at1on** [comment] 2016-01-21 20:40
@Yoldark34 thank you.

**Comment by Yoldark34** [comment] 2016-01-21 20:55
Ok, i did not reproduce the bug from 19 adresses but i did it with 30 addresses.

[debug_crash.log.txt](https://github.com/PaycoinFoundation/paycoin/files/99878/debug_crash.log.txt)

**Comment by Yoldark34** [comment] 2016-01-21 20:59
The crashed transaction is taking a lot of time to validate, but did validate after 1 hour normally.

**Comment by IngCr3at1on** [comment] 2016-01-21 21:06
Yeah see it's crashing when it attempts to relay the wtx which is what the other logs have shown. Still trying to work out an exact cause at this time...

**Comment by Yoldark34** [comment] 2016-01-21 21:07
:+1:

**Comment by mitchellcash** [comment] 2016-01-23 22:34
This does look the same to me. I got as far as it crashing when it attempts to relay the wtx as well but haven't made any progress as to why this happens to the larger transactions.

**Closed** 2016-01-26 22:19 UTC
Labels: bug, Windows
